### ISSUE TITLE
Installation fails - `patch-package: command not found`

### ISSUE THREAD

**Issue by jamesmbourne** [launchport/helix-flare#2]
Great ideas in this library!

When running `npm i helix-flare`, I get the error `sh: patch-package: command not found`.

It looks like the installation fails due to a missing dependency `patch-package` of the [postinstall](https://github.com/launchport/helix-flare/blob/main/package.json#L43) command.

For now, I have worked around this by installing the dependency myself with `npm i -D patch-package`.

**Comment by dan-lee** [comment]
Hey @jamesmbourne, thanks for your issue. 
That was an oversight and should not happen when you install the library of course!

This should be fixed in `v1.1.3` 🚀
